[package]
name = "my_project"
version = "0.1"
lean_version = "nightly-2018-08-23"
path = "src"

[dependencies]
mathlib = {git = "http://github.com/leanprover/mathlib", rev = "5c37507c58d95f93ef0f587b2de2dabd75daec12"}
